name: Auto Commit and Push

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  push_changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to commit & push changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents authentication conflicts

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Make Changes (Example)
        run: |
          echo "Last updated: $(date)" > last_update.txt  # Example change
          git add .
          git commit -m "Automated commit: Updated dropdown styles and layout fixes"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
